[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "norman-base-utils"
description = "norman utils common classes"
version = "0.0.1"
authors = [
    {name = "Yonatan Alon", email = "yonatankarimish@gmail.com"},
]

requires-python = ">=3.9"
license = {text = "proprietary"}
dependencies = []

[tools.setuptools]
packages = ["norman_base_utils"]
