name: Notify on merged PR to main

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
      - development
      - staging
      - github-actions-test-branch

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Google Chat
        env:
          CHAT_WEBHOOK: ${{ secrets.GCHAT_WEBHOOK }}
          REPO_NAME:    ${{ github.repository }}
          PR_TITLE:     ${{ github.event.pull_request.title }}
          PR_AUTHOR:    ${{ github.event.pull_request.user.login }}
          PR_URL:       ${{ github.event.pull_request.html_url }}
          BRANCH_NAME:  ${{ github.event.pull_request.head.ref }}
          PR_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          curl -X POST "$CHAT_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{
                \"text\": \"New update to the repository: *${REPO_NAME}*\n\nBranch: *${BRANCH_NAME}*\nDestination: *${PR_BASE_BRANCH}*\nAuthor: *${PR_AUTHOR}*\nPull request: *${PR_TITLE}*\nURL: ${PR_URL}\"
              }"
